@url = http://localhost:5121
@fake-url = http://localhost:5033

POST {{url}}/v1/users/
Accept: application/json
Content-Type: application/json

{
  "email": "client@eggek.com",
  "password": "@Test02",
  "role": "client"
}

###

GET {{url}}/v1/users/me
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###

POST {{url}}/v1/token/
Accept: application/json
Content-Type: application/json

{
  "email": "catalog2@eggek.com",
  "password": "@Test01"
}

> {%
    client.global.set("auth_token", response.body);
%}

###

POST {{url}}/v1/catalog/products/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Sample Product",
  "description": "This is a sample product description.",
  "price": 99.99,
  "quantityInStock": 50,
  "weightInGrams": 500,
  "heightInCentimeters": 10,
  "widthInCentimeters": 5
}

###

GET {{url}}/v1/catalog/products
Accept: application/json
Content-Type: application/json

###

GET {{url}}/v1/catalog/products/c99d69a9-5831-4672-a64e-af27a39e4bcc
Accept: application/json
Content-Type: application/json

###

PATCH {{url}}/v1/catalog/products/c99d69a9-5831-4672-a64e-af27a39e4bcc/stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "quantityInStock": 2
}

###

PATCH {{url}}/v1/catalog/products/c99d69a9-5831-4672-a64e-af27a39e4bcc/price
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "price": 10.40
}

###

POST {{fake-url}}/process-payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "amount": 100.50,
  "cardNumber": "1234567890123456",
  "cardholderName": "John Doe",
  "expirationDate": "2023-12-31",
  "cvv": "123"
}

###

POST {{fake-url}}/calculate-shipping
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Products": [
    {
      "weightInGrams": 500,
      "heightInCentimeters": 20,
      "widthInCentimeters": 15
    }
  ],
  "zipCode": "79000000"
}

###

POST {{url}}/v1/purchase/shopping-cart/add-product
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "productId": "b1ab7370-fc4f-4bbc-bcc9-58adc34b440f",
  "quantity": "2"
}

###

GET {{url}}/v1/purchase/shopping-cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

GET {{url}}/v1/purchase/shipping/cost/79000000
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

POST {{url}}/v1/purchase/checkout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "zipCode": "79000000",
  "cardNumber": "1234567890123456",
  "cardholderName": "John Doe",
  "expirationDate": "2024-12-31",
  "cvv": "123"
}





