@url = http://localhost:5121

POST {{url}}/v1/users/
Accept: application/json
Content-Type: application/json

{
  "email": "client@eggek.com",
  "password": "@Test02",
  "role": "client"
}

###

GET {{url}}/v1/users/me
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###

POST {{url}}/v1/token/
Accept: application/json
Content-Type: application/json

{
  "email": "catalog2@eggek.com",
  "password": "@Test01"
}

> {%
    client.global.set("auth_token", response.body);
%}

###

POST {{url}}/v1/catalog/products/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Sample Product",
  "description": "This is a sample product description.",
  "price": 99.99,
  "quantityInStock": 50,
  "weightInGrams": 500,
  "heightInCentimeters": 10,
  "widthInCentimeters": 5
}

###

PATCH {{url}}/v1/catalog/products/c99d69a9-5831-4672-a64e-af27a39e4bcc/stock
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "quantityInStock": 10
}

###

PATCH {{url}}/v1/catalog/products/c99d69a9-5831-4672-a64e-af27a39e4bcc/price
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "price": 10.50
}

###

